# file      : pgsql/native/buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

if ($build.meta_operation != 'dist')
{
  assert ($pgsql) "pgsql should be configured for this test"
  assert (!$multi) "multi-database mode is not supported by this test"
}

import libs  = libodb-pgsql%lib{odb-pgsql}
import libs += lib{common}

exe{driver}: {hxx cxx}{*} $libs testscript

cxx.poptions =+ "-I$out_base" "-I$src_base"

# Testscript's run-time prerequisites.
#
exe{driver}: ../../alias{pgsql-client}: include = adhoc
