# file      : buildfile
# license   : ODB NCUEL; see accompanying LICENSE file

./: {*/ -build/} \
    doc{NEWS README PACKAGE-README.md} \
    legal{NCUEL LICENSE} \
    manifest

# Don't install tests.
#
tests/: install = false
