# file      : buildfile
# license   : GNU GPL v3; see accompanying LICENSE file

./: {*/ -build/ -m4/} \
    doc{README PACKAGE-README.md NEWS} \
    legal{GPLv3 LICENSE} \
    manifest

# Don't install tests.
#
tests/: install = false
