# file      : buildfile
# license   : GNU GPL v3; see accompanying LICENSE file

./: {*/ -build/ -m4/} \
    doc{README.md PACKAGE-README.md NEWS} \
    legal{GPLv3 LICENSE} \
    manifest

# bbot worker hook script (see bindist-windows build configuration for
# details).
#
./: build/file{bindist-archive-post.bx}

# Don't install tests.
#
tests/: install = false
