# file      : buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

./: {*/ -build/ -boost/ -qt/} doc{README.md} legal{GPLv2 LICENSE} manifest

./: boost/: include = $boost
./: qt/:    include = $qt

./: testscript{*}: include = adhoc
