# file      : buildfile
# license   : not copyrighted - public domain

./: {*/ -build/ -boost/ -qt/} doc{README.md} legal{UNLICENSE LICENSE} manifest

./: boost/: include = $boost
./: qt/:    include = $qt

./: testscript{*}: include = adhoc
