# file      : sqlite/database/buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

if ($build.meta_operation != 'dist')
{
  assert ($sqlite) "sqlite should be configured for this test"
  assert (!$multi) "multi-database mode is not supported by this test"
}

import libs = libodb-sqlite%lib{odb-sqlite}

exe{driver}: {hxx cxx}{*} $libs testscript

cxx.poptions =+ "-I$out_base" "-I$src_base"
