# file      : mysql/native/buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

if ($build.meta_operation != 'dist')
{
  assert ($mysql) "mysql should be configured for this test"
  assert (!$multi) "multi-database mode is not supported by this test"
}

import libs  = libodb-mysql%lib{odb-mysql}
import libs += lib{common}

exe{driver}: {hxx cxx}{*} $libs testscript

cxx.poptions =+ "-I$out_base" "-I$src_base"

# Testscript's run-time prerequisites.
#
exe{driver}: ../../alias{mysql-client}: include = adhoc
