# file      : buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

./: libcommon/ common/ doc{README.md} legal{GPLv2 LICENSE} manifest

./: mysql/:  include = ($mysql  && !$multi)
./: sqlite/: include = ($sqlite && !$multi)
./: pgsql/:  include = ($pgsql  && !$multi)
./: oracle/: include = ($oracle && !$multi)
./: mssql/:  include = ($mssql  && !$multi)

./: evolution/: include = (!$multi)

./: boost/: include = $boost
./: qt/:    include = $qt

./: testscript{*}: include = adhoc
