# file      : tests/basics/buildfile
# copyright : Copyright (c) 2009-2018 Code Synthesis Tools CC
# license   : ODB NCUEL; see accompanying LICENSE file

import libs = libodb-mssql%lib{odb-mssql}

exe{driver}: {hxx cxx}{*} $libs
