# file      : tests/basics/buildfile
# copyright : Copyright (c) 2009-2018 Code Synthesis Tools CC
# license   : ODB NCUEL; see accompanying LICENSE file

import libs = libodb-oracle%lib{odb-oracle}

exe{driver}: {hxx cxx}{*} $libs
