# file      : tests/basics/buildfile
# copyright : Copyright (c) 2009-2015 Code Synthesis Tools CC
# license   : GNU GPL v2; see accompanying LICENSE file

import libs = libodb-pgsql%lib{odb-pgsql}

exe{driver}: cxx{driver} $libs
