# file      : common/definition/buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

import libodb = libodb%lib{odb}

libs =

for db: $databases
  import libs += libodb-$db%lib{odb-$db}

import libs += lib{common}

hdrs = test time-mapping

exe{driver}: {hxx cxx}{* -*-odb -*-odb-*} testscript

# Introduce the metadata library target to make sure the libodb library is
# resolved for the odb_compile ad hoc rule (see build/root.build for details).
#
libue{test-meta}: $libodb

for h: $hdrs
{
  exe{driver}: {hxx ixx cxx}{$h-odb}

  <{hxx ixx cxx}{$h-odb}>: hxx{$h} libue{test-meta}

  for db: $databases
  {
    exe{driver}: {hxx ixx cxx}{$h-odb-$db}: include = $multi
    <{hxx ixx cxx}{$h-odb-$db}>: hxx{$h} libue{test-meta}
  }
}

exe{driver}: libue{test-meta} $libs

# Specify the ODB custom options to be used by the odb_compile ad hoc rule
# (see build/root.build for details).
#
odb_options = --table-prefix definition_ \
              --generate-schema

<{hxx ixx cxx}{time-mapping-odb}>: odb_options =

for db: $databases
  {hxx ixx cxx}{time-mapping-odb-$db}: odb_options =

cxx.poptions =+ "-I$out_base" "-I$src_base"

# Testscript's run-time prerequisites.
#
exe{driver}: ../../alias{database-client}: include = adhoc
