# file      : odb/pgsql/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : GNU GPL v2; see accompanying LICENSE file

import int_libs = libodb%lib{odb}
import imp_libs = libpq%lib{pq}

lib{odb-pgsql}: {hxx ixx txx cxx}{* -version-build2} {hxx}{version-build2}   \
        details/{hxx ixx txx cxx}{* -options} details/{hxx ixx cxx}{options} \
 details/build2/{h}{*}                                                       \
                $imp_libs $int_libs

hxx{version-build2}: in{version-build2} $src_root/file{manifest}
hxx{version-build2}: dist = true

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version.
#
if $version.pre_release
  lib{odb-pgsql}: bin.lib.version = @"-$version.project_id"
else
  lib{odb-pgsql}: bin.lib.version = @"-$version.major.$version.minor"

cxx.poptions =+ "-I$out_root" "-I$src_root" -DLIBODB_PGSQL_BUILD2
obja{*}: cxx.poptions += -DLIBODB_PGSQL_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBODB_PGSQL_SHARED_BUILD

lib{odb-pgsql}: cxx.export.poptions = "-I$out_root" "-I$src_root" -DLIBODB_PGSQL_BUILD2
liba{odb-pgsql}: cxx.export.poptions += -DLIBODB_PGSQL_STATIC
libs{odb-pgsql}: cxx.export.poptions += -DLIBODB_PGSQL_SHARED

lib{odb-pgsql}: cxx.export.libs = $int_libs

details/:
{
  if $cli.configured
  {
    cli.cxx{options}: cli{options}

    cli.options += --include-with-brackets --include-prefix odb/pgsql/details \
--guard-prefix LIBODB_PGSQL_DETAILS --generate-file-scanner \
--cli-namespace odb::pgsql::details::cli --long-usage --generate-specifier

    # Include generated cli files into the distribution.
    #
    cli.cxx{*}: dist = true
  }

  # But don't install their headers since they are only used internally in the
  # database implementation.
  #
  {hxx ixx}{options}: install = false
}

# Install into the odb/pgsql/ subdirectory of, say, /usr/include/.
#
install.include = $install.include/odb/pgsql/
install.include.subdirs = true # Recreate subdirectories.

# We want these to be picked up even when LIBODB_PGSQL_BUILD2 is not defined.
#
hxx{version}@./:     install = false
hxx{version-build2}: install = $install.include/version.hxx

details/build2/:
{
  if ($cxx.id == "msvc")
  {
    h{config}@./:    install = false
    h{config-vc}@./: install = $install.include/details/
  }
  else
  {
    h{config}@./:    install = $install.include/details/
    h{config-vc}@./: install = false
  }
}
