# file      : odb/pgsql/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : GNU GPL v2; see accompanying LICENSE file

import int_libs = libodb%lib{odb}
import imp_libs = libpq%lib{pq}

lib{odb-pgsql}:                                                   \
               {hxx         cxx}{ auto-handle                   } \
               {hxx            }{ binding                       } \
               {hxx ixx     cxx}{ connection                    } \
               {hxx         cxx}{ connection-factory            } \
               {hxx     txx    }{ container-statements          } \
               {hxx ixx     cxx}{ database                      } \
               {hxx ixx     cxx}{ error                         } \
               {hxx         cxx}{ exceptions                    } \
               {hxx            }{ forward                       } \
               {hxx     txx    }{ no-id-object-result           } \
               {hxx     txx    }{ no-id-object-statements       } \
               {hxx            }{ pgsql-fwd                     } \
               {hxx            }{ pgsql-oid                     } \
               {hxx            }{ pgsql-types                   } \
               {hxx     txx    }{ polymorphic-object-result     } \
               {hxx     txx    }{ polymorphic-object-statements } \
               {hxx         cxx}{ prepared-query                } \
               {hxx ixx txx cxx}{ query                         } \
               {            cxx}{ query-const-expr              } \
               {hxx ixx txx cxx}{ query-dynamic                 } \
               {hxx     txx    }{ section-statements            } \
               {hxx     txx    }{ simple-object-result          } \
               {hxx ixx txx cxx}{ simple-object-statements      } \
               {hxx     txx    }{ statement-cache               } \
               {hxx         cxx}{ statement                     } \
               {hxx         cxx}{ statements-base               } \
               {hxx         cxx}{ tracer                        } \
               {hxx         cxx}{ traits                        } \
               {hxx            }{ traits-calls                  } \
               {hxx ixx     cxx}{ transaction                   } \
               {hxx ixx     cxx}{ transaction-impl              } \
               {hxx            }{ version                       } \
               {hxx     txx    }{ view-result                   } \
               {hxx     txx    }{ view-statements               } \
       details/{hxx            }{ config                        } \
       details/{hxx            }{ conversion                    } \
       details/{hxx         cxx}{ endian-traits                 } \
       details/{hxx            }{ export                        } \
       details/{hxx ixx     cxx}{ options                       } \
details/build2/{h              }{ config                        } \
details/build2/{h              }{ config-vc                     } \
                                  $imp_libs $int_libs

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version.
#
if $version.pre_release
  lib{odb-pgsql}: bin.lib.version = @"-$version.project_id"
else
  lib{odb-pgsql}: bin.lib.version = @"-$version.major.$version.minor"

cxx.poptions =+ "-I$out_root" "-I$src_root" -DLIBODB_PGSQL_BUILD2
obja{*}: cxx.poptions += -DLIBODB_PGSQL_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBODB_PGSQL_SHARED_BUILD

lib{odb-pgsql}: cxx.export.poptions = "-I$src_root" -DLIBODB_PGSQL_BUILD2
liba{odb-pgsql}: cxx.export.poptions += -DLIBODB_PGSQL_STATIC
libs{odb-pgsql}: cxx.export.poptions += -DLIBODB_PGSQL_SHARED

lib{odb-pgsql}: cxx.export.libs = $int_libs

details/:
{
  if $cli.configured
  {
    cli.cxx{options}: cli{options}

    cli.options += --include-with-brackets --include-prefix odb/pgsql/details \
--guard-prefix LIBODB_PGSQL_DETAILS --generate-file-scanner \
--cli-namespace odb::pgsql::details::cli --long-usage --generate-specifier

    # Include generated cli files into the distribution.
    #
    cli.cxx{*}: dist = true
  }

  # But don't install their headers since they are only used internally in the
  # database implementation.
  #
  {hxx ixx}{options}: install = false
}

# Install into the odb/pgsql/ subdirectory of, say, /usr/include/.
#
install.include = $install.include/odb/pgsql/
install.include.subdirs = true # Recreate subdirectories.

# We want these to be picked up even when LIBODB_PGSQL_BUILD2 is not defined.
#
details/build2/:
{
  if ($cxx.id == "msvc")
  {
    h{config}@./:    install = false
    h{config-vc}@./: install = $install.include/details/
  }
  else
  {
    h{config}@./:    install = $install.include/details/
    h{config-vc}@./: install = false
  }
}
