# file      : sqlite/stream/buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

if ($build.meta_operation != 'dist')
{
  assert ($sqlite) "sqlite should be configured for this test"
  assert (!$multi) "multi-database mode is not supported by this test"
}

import libodb        = libodb%lib{odb}
import libodb_sqlite = libodb-sqlite%lib{odb-sqlite}
import libs          = lib{common}

exe{driver}: {hxx cxx}{* -*-odb} {hxx ixx cxx}{test-odb} testscript

# Introduce the metadata library target to make sure the libodb and
# libodb-sqlite libraries are resolved for the odb_compile ad hoc rule (see
# build/root.build for details).
#
libue{test-meta}: $libodb $libodb_sqlite

<{hxx ixx cxx}{test-odb}>: hxx{test} libue{test-meta}

exe{driver}: libue{test-meta} $libs

# Specify the ODB custom options to be used by the odb_compile ad hoc rule
# (see build/root.build for details).
#
odb_options = --table-prefix sqlitex_stream_ \
              --generate-schema              \
              --default-database common      \
              --generate-query

cxx.poptions =+ "-I$out_base" "-I$src_base"
