# file      : buildfile
# license   : ODB NCUEL; see accompanying LICENSE file

./: {*/ -build/}\
    doc{README.md PACKAGE-README.md NEWS} \
    legal{NCUEL LICENSE} \
    manifest

# Don't install tests.
#
tests/: install = false
