# file      : common/transaction/basics/buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

import libs  = libodb%lib{odb}
import libs += lib{common}

exe{driver}: {hxx cxx}{*} $libs testscript

cxx.poptions =+ "-I$out_base" "-I$src_base"

# Testscript's run-time prerequisites.
#
exe{driver}: ../../../alias{database-client}: include = adhoc
