# file      : buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

./: {*/ -build/} \
    doc{README.md PACKAGE-README.md NEWS} \
    legal{LICENSE} \
    manifest

# Don't install tests.
#
tests/: install = false
