# file      : pgsql/bulk/buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

if ($build.meta_operation != 'dist')
{
  assert ($pgsql && !$multi) \
    "pgsql should be configured via config.odb_tests.database variable as a single database"

  assert ($pgsql_bulk) "bulk operations are disabled for pgsql"
}

import libodb = libodb%lib{odb}

import libs  = libpq%lib{pq}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += lib{common}

exe{driver}: {hxx cxx}{* -*-odb} {hxx ixx cxx}{test-odb} testscript

# Introduce the metadata library target to make sure the libodb library is
# resolved for the odb_compile ad hoc rule (see build/root.build for details).
#
libue{test-meta}: $libodb

<{hxx ixx cxx}{test-odb}>: hxx{test} libue{test-meta}

exe{driver}: libue{test-meta} $libs

# Specify the ODB custom options to be used by the odb_compile ad hoc rule
# (see build/root.build for details).
#
odb_options = --table-prefix pgsql_bulk_ \
              --generate-schema          \
              --generate-query

cxx.poptions =+ "-I$out_base" "-I$src_base"

# Testscript's run-time prerequisites.
#
exe{driver}: ../../alias{pgsql-client}: include = adhoc
