# file      : common/include/buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

import libodb = libodb%lib{odb}

libs =

for db: $databases
  import libs += libodb-$db%lib{odb-$db}

import libs += lib{common}

hdrs = obj1 obj2 obj3 test1 test2 test3 test4

exe{driver}: {hxx cxx}{* -*-odb -*-odb-*} testscript

# Introduce the metadata library target to make sure the libodb library is
# resolved for the odb_compile ad hoc rule (see build/root.build for details).
#
libue{test-meta}: $libodb

for h: $hdrs
{
  exe{driver}: {hxx ixx cxx}{$h-odb}

  <{hxx ixx cxx}{$h-odb}>: hxx{$h} libue{test-meta}

  for db: $databases
  {
    exe{driver}: {hxx ixx cxx}{$h-odb-$db}: include = $multi
    <{hxx ixx cxx}{$h-odb-$db}>: hxx{$h} libue{test-meta}
  }
}

exe{driver}: libue{test-meta} $libs

# Specify the ODB custom options to be used by the odb_compile ad hoc rule
# (see build/root.build for details). Also see driver.cxx for the details on
# the -I options usage.
#
odb_options = --table-prefix include_ \
              "-I$out_base"           \
              "-I$src_base/.."        \
              "-I$src_base/../.."

cxx.poptions =+ "-I$out_base" "-I$src_base"             \
                "-I$out_base/../.." "-I$src_base/../.."

# Testscript's run-time prerequisites.
#
exe{driver}: ../../alias{database-client}: include = adhoc
