# file      : buildfile
# license   : GNU GPL v2; see accompanying LICENSE file

./: {*/ -build/} \
    doc{NEWS README PACKAGE-README.md} \
    legal{GPLv2 LICENSE} \
    manifest

# Don't install tests.
#
tests/: install = false
